# - - - - - - - - - - - - - - #
# LogRenderer's configuration #
# - - - - - - - - - - - - - - #

# The port the web server will listen to
port: 8080
# The url prefix of the web interface (e.g. `/logrenderer` if the index of the application is `/logrenderer`). You can leave this empty if the index is the root of your website (`/`)
url-prefix: "/logrenderer"

# All the servers to register for logs watching
servers:
    serv_1:
        display-name: "Server 1"
        log-file-path: "/path/to/server_1/logs/latest.log"
        syntax-highlighting:
            -   field: "time"
                regex: '^\[\d{2}:\d{2}:\d{2}]'
            -   field: "info"
                regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/INFO]'
            -   field: "warn"
                regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/WARN]'
            -   field: "error"
                regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/ERROR]'
            -   field: "content"
                regex: '(?<=(^\[\d{2}:\d{2}:\d{2}] \[.{0,30}\/(INFO|WARN|ERROR)]: )).*$'
    counter:
        display-name: "Counter"
        log-file-path: "~/dir/counter-output.log"
        syntax-highlighting:
            -   field: "text"
                regex: '/.*/'