# - - - - - - - - - - - - - - #
# LogRenderer's configuration #
# - - - - - - - - - - - - - - #

# The port the web server will listen to
port: 8080
# The url prefix of the web interface (e.g. `/logrenderer` if the index of the application is `/logrenderer`). You can leave this empty if the index is the root of your website (`/`)
url-prefix: "/logrenderer"
# Whether debug logs should be printed or not
debug: true
# The delay before a new file watcher is started when a log file is reset/renamed
delay-before-rewatch: "10ms"

# All the servers to register for logs watching
servers:
    classic:
        -   server-tag: "serv_1"
            display-name: "Server 1"
            log-file-path: "/path/to/server_1/logs/latest.log"
            syntax-highlighting:
                -   field: "time"
                    regex: '^\[\d{2}:\d{2}:\d{2}]'
                -   field: "info"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/INFO]'
                -   field: "warn"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/WARN]'
                -   field: "error"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/ERROR]'
                -   field: "content"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}] \[.{0,30}\/(INFO|WARN|ERROR)]: )).*$'
                archived-logs-dir-path: "/path/to/server_1/logs"
                # The archived log reader supports plain text and gzip plain text files
                archive-log-filename-format: "*.log.gz"
        -   server-tag: "counter"
            display-name: "Counter"
            log-file-path: "~/dir/counter-output.log"
            syntax-highlighting:
                -   field: "text"
                    regex: '/.*/'
    dynamic:
        -   server-tag: "paper"
            display-name: "Paper %id%"
            # The pattern of the instances log file, it can contain joker characters like '*'
            log-file-pattern: "/path/to/DynamicServers/Paper_*/logs/latest.log"
            # The regular expression to extract the instance identifier from the log file path
            instance-identifier: ".*/Paper_(?P<id>\\d*)/logs/latest\\.log"
            syntax-highlighting:
                -   field: "time"
                    regex: '^\[\d{2}:\d{2}:\d{2}]'
                -   field: "info"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/INFO]'
                -   field: "warn"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/WARN]'
                -   field: "error"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}]) )\[.{0,30}\/ERROR]'
                -   field: "content"
                    regex: '(?<=(^\[\d{2}:\d{2}:\d{2}] \[.{0,30}\/(INFO|WARN|ERROR)]: )).*$'