name: "Build & Test"

on:
    push:
        branches: [ master, dev ]
    pull_request:
        branches: [ master, dev ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: [ "1.18", "1.19" ]
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go ${{ matrix.go }}
                uses: actions/setup-go@v3.2.0
                with:
                    go-version: ${{ matrix.go }}

            -   name: Build
                run: go build -o out -v ./...
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: [ "1.18", "1.19" ]
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go ${{ matrix.go }}
                uses: actions/setup-go@v3.2.0
                with:
                    go-version: ${{ matrix.go }}

            -   name: Test
                run: go test -v ./...
