name: Build

on:
    push:
        branches: [ master, dev ]
    pull_request:
        branches: [ master, dev ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v3.2.0
                with:
                    go-version: 1.18

            -   name: Build & Test
                run: go build -o out -v ./...
