name: Lint

on:
    push:
        branches: [ master, dev ]
    pull_request:
        branches: [ master, dev ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v3.2.0
